[package]
name = "stream_town_tools"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bevy.workspace = true
bevy-inspector-egui.workspace = true
bevy_egui.workspace = true
ron.workspace = true
stream_town_domain = { path = "../stream_town_domain" }
stream_town_game = { path = "../stream_town_game" }
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
