use super::*;

pub(super) struct GameplayFlowPlugin;

impl Plugin for GameplayFlowPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(
            OnEnter(GameState::InGame),
            (
                reset_gameplay_attention_runtime,
                begin_world_reveal,
                spawn_level_up_toast,
                spawn_menu_overlay,
            ),
        )
        .add_systems(
            Update,
            (
                animate_loading_icon,
                finish_world_reveal
                    .after(apply_material_overrides)
                    .after(tag_cosmetic_renderers)
                    .after(attach_native_animations)
                    .after(attach_converted_animations),
                sync_loading_screen_status
                    .after(finish_world_reveal)
                    .run_if(resource_exists::<WorldLoadingRuntime>),
                load_input
                    .after(finish_world_reveal)
                    .before(enforce_loading_overlay_retired)
                    .run_if(world_reveal_finished),
                enforce_loading_overlay_retired.after(finish_world_reveal),
                confirm_gameplay_ready.after(enforce_loading_overlay_retired),
            )
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                correct_player_rig_axis,
                debug_player_model_bounds.after(correct_player_rig_axis),
                tag_equipment_nodes,
                sync_equipment_nodes
                    .after(tag_equipment_nodes)
                    .after(correct_player_rig_axis)
                    .after(animate_agents)
                    .after(drive_converted_animations),
                tag_enemy_model_nodes,
                tag_cosmetic_nodes,
                sync_cosmetic_nodes.after(tag_cosmetic_nodes),
                tag_cosmetic_renderers.after(apply_material_overrides),
                sync_cosmetic_materials
                    .after(tag_cosmetic_renderers)
                    .after(apply_material_overrides),
                refresh_building_visual_signatures
                    .after(move_agents)
                    .before(sync_building_presentation)
                    .in_set(AgentSimulationSet),
                tag_building_model_nodes.after(sync_building_presentation),
                sync_building_model_nodes.after(tag_building_model_nodes),
                tag_authored_rotating_nodes.after(tag_building_model_nodes),
                rotate_authored_building_nodes
                    .after(tag_authored_rotating_nodes)
                    .after(sync_building_model_nodes)
                    .in_set(GameplaySimulationSet),
                sync_tiled_building_rotation.after(sync_building_presentation),
                sync_chimney_smoke_emitters.after(sync_building_presentation),
            )
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                update_tower_shooters.after(move_agents),
                move_combat_projectiles.after(update_tower_shooters),
                animate_combat_effects.after(move_combat_projectiles),
                repeat_combat_smoke.after(animate_combat_effects),
                emit_damaged_building_effects.after(move_agents),
                animate_building_effects.after(emit_damaged_building_effects),
                repeat_building_smoke.after(animate_building_effects),
                emit_chimney_smoke.after(sync_chimney_smoke_emitters),
                animate_chimney_smoke_particles.after(emit_chimney_smoke),
                update_enemy_encounters.after(move_combat_projectiles),
                announce_citizen_deaths
                    .after(move_agents)
                    .after(move_combat_projectiles),
                track_camera_damage_focus
                    .after(move_agents)
                    .after(move_combat_projectiles),
                restart_world_after_town_hall_falls.after(move_agents),
                sync_pooled_night_lights
                    .after(move_combat_projectiles)
                    .after(sync_building_presentation)
                    .in_set(NightLightSyncSet),
                sync_fish_god_presentation
                    .after(update_enemy_encounters)
                    .after(process_injected_commands),
                emit_falling_fish.after(sync_fish_god_presentation),
                animate_falling_fish.after(emit_falling_fish),
                drive_fish_god_exit
                    .after(sync_fish_god_presentation)
                    .before(drive_converted_animations),
            )
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                (
                    reset_crowd_separation,
                    refresh_station_target_runtime,
                    sync_fine_navigation,
                    refresh_enemy_navigation,
                    move_agents.after(correct_player_rig_axis),
                    apply_crowd_separation,
                    update_agent_locomotion,
                )
                    .chain()
                    .in_set(AgentSimulationSet),
                sync_resource_nodes.after(move_agents),
                sync_building_presentation
                    .after(move_agents)
                    .in_set(AgentSimulationSet),
                animate_agents.in_set(GameplaySimulationSet),
                resolve_native_animation_requests.after(upgrade_actor_placeholders),
                attach_native_animations,
                attach_converted_animations
                    .after(upgrade_actor_placeholders)
                    .after(sync_active_pets)
                    .after(sync_fish_god_presentation)
                    .after(correct_player_rig_axis),
                drive_native_animations
                    .after(update_agent_locomotion)
                    .in_set(GameplaySimulationSet),
                drive_converted_animations
                    .after(update_agent_locomotion)
                    .after(attach_converted_animations)
                    .in_set(AgentSimulationSet),
                update_environment_presentation.after(move_agents),
                animate_weather_particles
                    .after(update_environment_presentation)
                    .in_set(GameplaySimulationSet),
                follow_animation_closeup_camera
                    .after(move_agents)
                    .in_set(GameplaySimulationSet),
                sync_active_pets.after(move_agents),
                camera_zoom_and_commands
                    .after(process_injected_commands)
                    .after(track_camera_damage_focus)
                    .after(follow_animation_closeup_camera)
                    .after(follow_pet_closeup_camera)
                    .in_set(GameplaySimulationSet),
                select_grid_cell
                    .run_if(resource_exists::<PointerObjectSelectionEnabled>)
                    .in_set(GameplaySimulationSet),
                inject_environment_commands.in_set(GameplaySimulationSet),
                save_input
                    .after(apply_agent_commands)
                    .after(apply_building_commands)
                    .in_set(GameplaySimulationSet),
                drive_level_up_presentation
                    .after(move_agents)
                    .in_set(GameplaySimulationSet),
                update_hud,
            )
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            sync_guardhouse_defenders
                .after(process_injected_commands)
                .before(move_agents)
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            enforce_recruit_role_level_cap
                .after(move_agents)
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            follow_pet_closeup_camera
                .after(move_agents)
                .after(sync_active_pets)
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            repair_replaced_converted_animation_instances
                .before(attach_converted_animations)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                report_animation_binding_diagnostics,
                report_animation_loop_diagnostics,
            )
                .after(drive_converted_animations)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            PostUpdate,
            (
                report_pre_animation_stage.before(AnimationSystems),
                report_post_animation_stage
                    .after(AnimationSystems)
                    .before(TransformSystems::Propagate),
                report_live_skin_deformation.after(TransformSystems::Propagate),
            )
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            animate_fish_school
                .in_set(AgentSimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                capture_foliage_acceptance
                    .after(camera_zoom_and_commands)
                    .after(finish_world_reveal),
                sync_world_render_lod.after(capture_foliage_acceptance),
            )
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                attach_gate_animations.after(sync_building_presentation),
                drive_gate_animations
                    .after(move_agents)
                    .after(attach_gate_animations)
                    .in_set(GameplaySimulationSet),
            )
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                sync_selection_outline.after(select_grid_cell),
                update_selection_panel.after(select_grid_cell),
                announce_ruler_vote_result.after(move_agents),
                announce_community_vote_results.after(move_agents),
                start_scheduled_technology_vote.after(move_agents),
                announce_technology_vote
                    .after(start_scheduled_technology_vote)
                    .after(process_injected_commands),
                update_vote_panels
                    .after(announce_ruler_vote_result)
                    .after(announce_community_vote_results)
                    .after(announce_technology_vote),
                update_current_event_panel.after(update_enemy_encounters),
            )
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                drive_world_audio.after(update_environment_presentation),
                tidal_music::update_enemy_music_intensity.after(move_agents),
                tidal_music::drive_tidal_music
                    .after(drive_world_audio)
                    .after(tidal_music::update_enemy_music_intensity),
                drive_seagull_flight.after(tidal_music::drive_tidal_music),
            )
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                sync_actor_name_overlays,
                sync_actor_health_overlays,
                sync_building_health_overlays,
                sync_temporary_world_labels,
            )
                .chain()
                .after(move_agents)
                .in_set(AgentSimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                menu_input,
                game_menu_buttons.in_set(AccessibilityActionDispatch),
                update_game_menu_controls,
                settings_tab_buttons.in_set(AccessibilityActionDispatch),
                settings_value_buttons.in_set(AccessibilityActionDispatch),
                settings_action_buttons.in_set(AccessibilityActionDispatch),
                (rebuild_settings_rows, update_settings_value_rows).chain(),
                update_settings_controls,
                update_menu_overlay,
                (
                    spawn_loading_screen,
                    begin_world_loading_cover,
                    advance_world_loading_cover,
                )
                    .chain()
                    .run_if(world_loading_cover_requested),
            )
                .chain()
                .after(inject_environment_commands)
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            animate_healing_effects
                .after(move_agents)
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            autosave_game
                .after(move_agents)
                .after(apply_agent_commands)
                .after(apply_building_commands)
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                instantiate_building_materials.after(apply_material_overrides),
                sync_building_material_instances
                    .after(instantiate_building_materials)
                    .in_set(AgentSimulationSet),
            )
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            Update,
            (
                process_injected_commands.after(inject_environment_commands),
                start_queued_town_event.after(process_injected_commands),
                apply_agent_commands.after(process_injected_commands),
                animate_ping_pointers
                    .after(move_agents)
                    .after(apply_agent_commands),
                apply_building_commands.after(process_injected_commands),
                expire_inactive_building_placements.after(process_injected_commands),
                sync_building_placers.after(expire_inactive_building_placements),
                apply_building_placement_ghosts.after(sync_building_placers),
                decay_traversal_wear.after(move_agents),
                sync_traversal_wear_texture.after(decay_traversal_wear),
                sync_path_surface_texture
                    .after(apply_building_commands)
                    .before(move_agents),
                sync_building_placement_overlays
                    .after(process_injected_commands)
                    .after(apply_building_placement_ghosts),
                sync_foliage_clearance
                    .after(apply_building_commands)
                    .after(decay_traversal_wear)
                    .after(sync_path_surface_texture)
                    .after(ground_loaded_surface_visuals),
                sync_world_diagnostic_view
                    .after(process_injected_commands)
                    .after(sync_fine_navigation)
                    .after(sync_resource_nodes)
                    .after(sync_building_presentation),
            )
                .in_set(GameplaySimulationSet)
                .run_if(in_state(GameState::InGame)),
        )
        .add_systems(
            OnExit(GameState::InGame),
            (
                tidal_music::stop_tidal_music,
                save_on_gameplay_exit,
                cleanup_world,
                cleanup_menu_overlay,
            )
                .chain(),
        );
    }
}
