use super::*;

pub struct StreamTownGamePlugin;

impl Plugin for StreamTownGamePlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(TabNavigationPlugin);
        app.add_plugins(runtime::timelapse::CityTimelapsePlugin);
        #[cfg(target_os = "windows")]
        app.add_plugins(direct_broadcast::DirectTwitchBroadcastPlugin);
        let render_schedule_available = app.get_sub_app(RenderApp).is_some();
        let presented_frames = PresentedRenderFrames::new(render_schedule_available);
        let gpu_readiness = GpuReadinessProbe::default();
        let automatic_resume_path = automatic_resume_save_path();
        let fixed_save_path = std::env::var_os("STREAM_TOWN_SAVE_PATH").map(PathBuf::from);
        let requested_new_town = if automatic_resume_path.is_none() {
            std::env::var("STREAM_TOWN_NEW_TOWN_NAME")
                .ok()
                .filter(|name| !name.trim().is_empty())
        } else {
            None
        };
        app.insert_resource(presented_frames.clone());
        app.insert_resource(gpu_readiness.clone());
        if let Some(render_app) = app.get_sub_app_mut(RenderApp) {
            render_app
                .insert_resource(presented_frames)
                .insert_resource(gpu_readiness)
                .add_systems(
                    Render,
                    (record_gpu_readiness, record_presented_render_frame)
                        .chain()
                        .in_set(RenderSystems::Cleanup),
                );
        }
        if !app.world().contains_resource::<RuntimeConfig>() {
            app.insert_resource(RuntimeConfig(GameConfig::default()));
        }
        // Select the final seed before any world geometry exists so terrain,
        // water, resources, fish, and foliage all share one world. A named new
        // town uses the same stable seed derivation as the interactive menu.
        let startup_seed = requested_new_town
            .as_deref()
            .map(town_name_seed)
            .or_else(|| automatic_resume_world_seed(automatic_resume_path.as_deref()));
        if let Some(seed) = startup_seed {
            app.world_mut().resource_mut::<RuntimeConfig>().0.world.seed = seed;
        }
        if !app.world().contains_resource::<RuntimeContent>() {
            app.insert_resource(RuntimeContent(embedded_content()));
        }
        if !app.world().contains_resource::<RuntimePresentation>() {
            app.insert_resource(RuntimePresentation(embedded_presentation()));
        }
        if !app.world().contains_resource::<RuntimeAssetRoot>() {
            app.insert_resource(RuntimeAssetRoot(locate_asset_root()));
        }
        if !app.world().contains_resource::<RuntimePlayerSettings>() {
            app.insert_resource(RuntimePlayerSettings(PlayerSettings::default()));
        }
        app.add_message::<AccessibilityActionRequest>();
        app.init_state::<GameState>()
            .configure_sets(
                Update,
                GameplaySimulationSet
                    .run_if(in_state(GameState::InGame))
                    .run_if(resource_exists::<GameplayReady>),
            )
            .configure_sets(
                Update,
                AgentSimulationSet
                    .in_set(GameplaySimulationSet)
                    .run_if(agent_simulation_due),
            )
            .configure_sets(
                Update,
                NightLightSyncSet
                    .in_set(GameplaySimulationSet)
                    .run_if(night_light_sync_due),
            )
            .init_resource::<SessionStats>()
            .init_resource::<WorldRenderStats>()
            .init_resource::<TraversalWearRuntime>()
            .init_resource::<PathSurfaceRuntime>()
            .init_resource::<AgentSimulationCadence>()
            .init_resource::<FineNavigationRuntime>()
            .init_resource::<WorldDiagnosticRuntime>()
            .init_resource::<CrowdSeparationRuntime>()
            .init_resource::<StationTargetRuntime>()
            .init_resource::<StationResourceTargetIndex>()
            .init_resource::<EnemyNavigationRuntime>()
            .init_resource::<RegenerationRoleRuntime>()
            .init_resource::<RulerVoteAnnouncementRuntime>()
            .init_resource::<CitizenDeathAnnouncementRuntime>()
            .init_resource::<InjectedCommands>()
            .init_resource::<CommandFeedback>()
            .init_resource::<CommandAcknowledgementRuntime>()
            .init_resource::<CameraDamageRuntime>()
            .init_resource::<RetreatingCitizens>()
            .init_resource::<MenuRuntime>()
            .init_resource::<TownRestartRuntime>()
            .init_resource::<NightEnemyWaveRuntime>()
            .init_resource::<SettingsUiCache>()
            .init_resource::<SecretsRuntime>()
            .init_resource::<SensitiveScreenActive>()
            .init_resource::<AccessibilityRuntime>()
            .init_resource::<InputFocus>()
            .init_resource::<InputFocusVisible>()
            .init_resource::<MenuIoRequest>()
            .init_resource::<RuntimeConsoleRuntime>()
            .init_resource::<RuntimeCaptureRequest>()
            .init_resource::<CameraCommandQueue>()
            .init_resource::<AgentCommandQueue>()
            .init_resource::<BuildingCommandQueue>()
            .init_resource::<BuildingPlacers>()
            .init_resource::<PathFailureRuntime>()
            .init_resource::<TwitchConnection>()
            .init_resource::<OperatorChatRuntime>()
            .init_resource::<SelectedCell>()
            .init_resource::<SelectedActor>()
            .init_resource::<EnvironmentPresentation>()
            .init_resource::<PostProcessPresentation>()
            .init_resource::<BuildingMaterialInstances>()
            .init_resource::<BuildingMaterialUpdateRuntime>()
            .init_resource::<BuildingVisualSignatures>()
            .init_resource::<CosmeticMaterialCache>()
            .init_resource::<CharacterBaseMaterialCache>()
            .init_resource::<RoleActionAudioCache>()
            .init_resource::<WorldAudioRuntime>()
            .init_resource::<tidal_music::TidalMusicRuntime>()
            .init_resource::<tidal_music::IntensitySongInput>()
            .init_resource::<NativeAnimationCache>()
            .init_resource::<ConvertedAnimationCache>()
            .init_resource::<GateAnimationCache>()
            .init_resource::<LevelUpPresentation>()
            .add_observer(mark_converted_animation_instance_ready)
            .insert_resource(PlayerSettingsRuntime {
                autosave_elapsed_seconds: 0.0,
            })
            .insert_resource(TownSaveCatalogRuntime::from_startup_paths(
                fixed_save_path.clone(),
                automatic_resume_path.clone(),
            ))
            .insert_resource(SaveRuntime {
                store: NativeSaveStore::new(startup_save_path(
                    automatic_resume_path.clone(),
                    fixed_save_path,
                )),
            })
            .insert_resource(AutomaticResumeRuntime::new(automatic_resume_path))
            .add_systems(
                Startup,
                (
                    setup_rendering,
                    setup_accessibility,
                    (spawn_loading_screen, begin_menu_loading)
                        .chain()
                        .after(setup_rendering),
                    setup_world_audio_sources.after(setup_rendering),
                    initialize_twitch_account_state,
                    start_twitch_transport,
                    apply_player_settings.after(setup_rendering),
                    sync_authored_post_processing.after(apply_player_settings),
                ),
            )
            .add_systems(
                Update,
                (
                    animate_loading_icon,
                    poll_menu_loading,
                    sync_boot_loading_screen,
                )
                    .chain()
                    .run_if(in_state(GameState::Boot)),
            )
            .add_systems(
                OnEnter(GameState::MainMenu),
                (
                    spawn_loading_screen,
                    ensure_main_menu_loading,
                    spawn_main_menu,
                    spawn_menu_overlay,
                )
                    .chain(),
            )
            .add_systems(
                Update,
                upgrade_actor_placeholders
                    .after(generate_and_spawn_world)
                    .before(sync_gpu_world_expectations)
                    .run_if(in_state(GameState::WorldLoading).or_else(in_state(GameState::InGame)))
                    .run_if(resource_exists::<WorldRuntime>),
            )
            .add_systems(
                Update,
                (
                    poll_twitch_transport,
                    twitch_connection_input,
                    process_runtime_console,
                    publish_runtime_console_status.after(process_runtime_console),
                    capture_screenshot,
                    report_frame_time_gate,
                    apply_authored_ui_fonts,
                ),
            )
            .add_systems(PostUpdate, sync_cursor_visibility)
            .add_systems(
                Update,
                (
                    (tag_accessible_buttons, tag_accessible_text).chain(),
                    enhance_accessible_buttons.after(tag_accessible_buttons),
                    prune_decorative_accessibility_nodes,
                    accessibility_input
                        .after(tag_accessible_buttons)
                        .before(AccessibilityActionDispatch),
                    sync_accessibility_focus_visuals.after(accessibility_input),
                    sync_accessibility_contrast,
                    sync_accessibility_preferences,
                    announce_accessibility_state,
                ),
            )
            .add_systems(
                Update,
                (
                    (
                        main_menu_input.in_set(AccessibilityActionDispatch),
                        main_menu_buttons.in_set(AccessibilityActionDispatch),
                        update_main_menu_buttons,
                        town_dialog_buttons.in_set(AccessibilityActionDispatch),
                        update_town_dialog_ui,
                        scroll_town_load_list,
                    )
                        .chain(),
                    menu_input,
                    (
                        secrets_buttons.in_set(AccessibilityActionDispatch),
                        poll_secrets_authorization,
                        update_secrets_ui,
                        sync_sensitive_screen_active.in_set(SensitiveScreenUpdateSet),
                    )
                        .chain(),
                    settings_tab_buttons.in_set(AccessibilityActionDispatch),
                    settings_value_buttons.in_set(AccessibilityActionDispatch),
                    settings_action_buttons.in_set(AccessibilityActionDispatch),
                    (rebuild_settings_rows, update_settings_value_rows).chain(),
                    update_settings_controls,
                    update_menu_overlay,
                    (
                        spawn_loading_screen,
                        begin_world_loading_cover,
                        advance_world_loading_cover,
                    )
                        .chain()
                        .run_if(world_loading_cover_requested),
                    (
                        animate_loading_icon,
                        spawn_main_menu_incrementally,
                        finish_menu_reveal,
                    )
                        .chain(),
                    sync_boot_loading_screen,
                    animate_fish_school,
                    animate_main_menu_clouds,
                    hide_main_menu_inactive_model_nodes,
                    enforce_main_menu_building_shadow_casters,
                    tag_main_menu_rotating_nodes,
                    rotate_main_menu_nodes
                        .after(tag_main_menu_rotating_nodes)
                        .after(hide_main_menu_inactive_model_nodes),
                )
                    .chain()
                    .run_if(in_state(GameState::MainMenu)),
            )
            .add_systems(
                Update,
                (
                    go_live_confirmation_buttons.in_set(AccessibilityActionDispatch),
                    update_go_live_confirmation_ui,
                )
                    .chain()
                    .after(main_menu_buttons)
                    .run_if(in_state(GameState::MainMenu)),
            )
            .add_systems(
                Update,
                smoke_start_new_game_after_menu_reveal
                    .after(finish_menu_reveal)
                    .before(go_live_confirmation_buttons)
                    .run_if(in_state(GameState::MainMenu)),
            )
            .add_systems(
                Update,
                apply_material_overrides.run_if(in_rendered_game_state),
            )
            .add_systems(OnExit(GameState::MainMenu), cleanup_state_entities)
            .add_systems(
                OnEnter(GameState::WorldLoading),
                (
                    cleanup_loading_runtime,
                    restore_town_camera_for_world,
                    spawn_loading_screen,
                    begin_world_loading,
                )
                    .chain(),
            )
            .add_systems(
                Update,
                (
                    animate_loading_icon,
                    poll_world_loading,
                    generate_and_spawn_world.after(poll_world_loading),
                    sync_gpu_world_expectations.after(apply_material_overrides),
                    advance_loading_phase,
                    sync_loading_screen_status,
                )
                    .chain()
                    .run_if(in_state(GameState::WorldLoading)),
            )
            .add_systems(
                OnEnter(GameState::InGame),
                (
                    reset_gameplay_attention_runtime,
                    begin_world_reveal,
                    spawn_level_up_toast,
                    spawn_menu_overlay,
                ),
            )
            .add_systems(
                Update,
                (
                    animate_loading_icon,
                    finish_world_reveal
                        .after(apply_material_overrides)
                        .after(tag_cosmetic_renderers)
                        .after(attach_native_animations)
                        .after(attach_converted_animations),
                    sync_loading_screen_status
                        .after(finish_world_reveal)
                        .run_if(resource_exists::<WorldLoadingRuntime>),
                    load_input
                        .after(finish_world_reveal)
                        .before(enforce_loading_overlay_retired)
                        .run_if(world_reveal_finished),
                    enforce_loading_overlay_retired.after(finish_world_reveal),
                    confirm_gameplay_ready.after(enforce_loading_overlay_retired),
                )
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    correct_player_rig_axis,
                    debug_player_model_bounds.after(correct_player_rig_axis),
                    tag_equipment_nodes,
                    sync_equipment_nodes
                        .after(tag_equipment_nodes)
                        .after(correct_player_rig_axis)
                        .after(animate_agents)
                        .after(drive_converted_animations),
                    tag_enemy_model_nodes,
                    tag_cosmetic_nodes,
                    sync_cosmetic_nodes.after(tag_cosmetic_nodes),
                    tag_cosmetic_renderers.after(apply_material_overrides),
                    sync_cosmetic_materials
                        .after(tag_cosmetic_renderers)
                        .after(apply_material_overrides),
                    refresh_building_visual_signatures
                        .after(move_agents)
                        .before(sync_building_presentation)
                        .in_set(AgentSimulationSet),
                    tag_building_model_nodes.after(sync_building_presentation),
                    sync_building_model_nodes.after(tag_building_model_nodes),
                    tag_authored_rotating_nodes.after(tag_building_model_nodes),
                    rotate_authored_building_nodes
                        .after(tag_authored_rotating_nodes)
                        .after(sync_building_model_nodes)
                        .in_set(GameplaySimulationSet),
                    sync_tiled_building_rotation.after(sync_building_presentation),
                    sync_chimney_smoke_emitters.after(sync_building_presentation),
                )
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    update_tower_shooters.after(move_agents),
                    move_combat_projectiles.after(update_tower_shooters),
                    animate_combat_effects.after(move_combat_projectiles),
                    repeat_combat_smoke.after(animate_combat_effects),
                    emit_damaged_building_effects.after(move_agents),
                    animate_building_effects.after(emit_damaged_building_effects),
                    repeat_building_smoke.after(animate_building_effects),
                    emit_chimney_smoke.after(sync_chimney_smoke_emitters),
                    animate_chimney_smoke_particles.after(emit_chimney_smoke),
                    update_enemy_encounters.after(move_combat_projectiles),
                    announce_citizen_deaths
                        .after(move_agents)
                        .after(move_combat_projectiles),
                    track_camera_damage_focus
                        .after(move_agents)
                        .after(move_combat_projectiles),
                    restart_world_after_town_hall_falls.after(move_agents),
                    sync_pooled_night_lights
                        .after(move_combat_projectiles)
                        .after(sync_building_presentation)
                        .in_set(NightLightSyncSet),
                    sync_fish_god_presentation
                        .after(update_enemy_encounters)
                        .after(process_injected_commands),
                    emit_falling_fish.after(sync_fish_god_presentation),
                    animate_falling_fish.after(emit_falling_fish),
                    drive_fish_god_exit
                        .after(sync_fish_god_presentation)
                        .before(drive_converted_animations),
                )
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    (
                        reset_crowd_separation,
                        refresh_station_target_runtime,
                        sync_fine_navigation,
                        refresh_enemy_navigation,
                        move_agents.after(correct_player_rig_axis),
                        apply_crowd_separation,
                        update_agent_locomotion,
                    )
                        .chain()
                        .in_set(AgentSimulationSet),
                    sync_resource_nodes.after(move_agents),
                    sync_building_presentation
                        .after(move_agents)
                        .in_set(AgentSimulationSet),
                    animate_agents.in_set(GameplaySimulationSet),
                    resolve_native_animation_requests.after(upgrade_actor_placeholders),
                    attach_native_animations,
                    attach_converted_animations
                        .after(upgrade_actor_placeholders)
                        .after(sync_active_pets)
                        .after(sync_fish_god_presentation)
                        .after(correct_player_rig_axis),
                    drive_native_animations
                        .after(update_agent_locomotion)
                        .in_set(GameplaySimulationSet),
                    drive_converted_animations
                        .after(update_agent_locomotion)
                        .after(attach_converted_animations)
                        .in_set(AgentSimulationSet),
                    update_environment_presentation.after(move_agents),
                    animate_weather_particles
                        .after(update_environment_presentation)
                        .in_set(GameplaySimulationSet),
                    follow_animation_closeup_camera
                        .after(move_agents)
                        .in_set(GameplaySimulationSet),
                    sync_active_pets.after(move_agents),
                    camera_zoom_and_commands
                        .after(process_injected_commands)
                        .after(track_camera_damage_focus)
                        .after(follow_animation_closeup_camera)
                        .after(follow_pet_closeup_camera)
                        .in_set(GameplaySimulationSet),
                    select_grid_cell
                        .run_if(resource_exists::<PointerObjectSelectionEnabled>)
                        .in_set(GameplaySimulationSet),
                    inject_environment_commands.in_set(GameplaySimulationSet),
                    save_input
                        .after(apply_agent_commands)
                        .after(apply_building_commands)
                        .in_set(GameplaySimulationSet),
                    drive_level_up_presentation
                        .after(move_agents)
                        .in_set(GameplaySimulationSet),
                    update_hud,
                )
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                sync_guardhouse_defenders
                    .after(process_injected_commands)
                    .before(move_agents)
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                enforce_recruit_role_level_cap
                    .after(move_agents)
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                follow_pet_closeup_camera
                    .after(move_agents)
                    .after(sync_active_pets)
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                repair_replaced_converted_animation_instances
                    .before(attach_converted_animations)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    report_animation_binding_diagnostics,
                    report_animation_loop_diagnostics,
                )
                    .after(drive_converted_animations)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                PostUpdate,
                (
                    report_pre_animation_stage.before(AnimationSystems),
                    report_post_animation_stage
                        .after(AnimationSystems)
                        .before(TransformSystems::Propagate),
                    report_live_skin_deformation.after(TransformSystems::Propagate),
                )
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                animate_fish_school
                    .in_set(AgentSimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    capture_foliage_acceptance
                        .after(camera_zoom_and_commands)
                        .after(finish_world_reveal),
                    sync_world_render_lod.after(capture_foliage_acceptance),
                )
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    attach_gate_animations.after(sync_building_presentation),
                    drive_gate_animations
                        .after(move_agents)
                        .after(attach_gate_animations)
                        .in_set(GameplaySimulationSet),
                )
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    sync_selection_outline.after(select_grid_cell),
                    update_selection_panel.after(select_grid_cell),
                    announce_ruler_vote_result.after(move_agents),
                    announce_community_vote_results.after(move_agents),
                    start_scheduled_technology_vote.after(move_agents),
                    announce_technology_vote
                        .after(start_scheduled_technology_vote)
                        .after(process_injected_commands),
                    update_vote_panels
                        .after(announce_ruler_vote_result)
                        .after(announce_community_vote_results)
                        .after(announce_technology_vote),
                    update_current_event_panel.after(update_enemy_encounters),
                )
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    drive_world_audio.after(update_environment_presentation),
                    tidal_music::update_enemy_music_intensity.after(move_agents),
                    tidal_music::drive_tidal_music
                        .after(drive_world_audio)
                        .after(tidal_music::update_enemy_music_intensity),
                    drive_seagull_flight.after(tidal_music::drive_tidal_music),
                )
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    sync_actor_name_overlays,
                    sync_actor_health_overlays,
                    sync_building_health_overlays,
                    sync_temporary_world_labels,
                )
                    .chain()
                    .after(move_agents)
                    .in_set(AgentSimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    menu_input,
                    game_menu_buttons.in_set(AccessibilityActionDispatch),
                    update_game_menu_controls,
                    settings_tab_buttons.in_set(AccessibilityActionDispatch),
                    settings_value_buttons.in_set(AccessibilityActionDispatch),
                    settings_action_buttons.in_set(AccessibilityActionDispatch),
                    (rebuild_settings_rows, update_settings_value_rows).chain(),
                    update_settings_controls,
                    update_menu_overlay,
                    (
                        spawn_loading_screen,
                        begin_world_loading_cover,
                        advance_world_loading_cover,
                    )
                        .chain()
                        .run_if(world_loading_cover_requested),
                )
                    .chain()
                    .after(inject_environment_commands)
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                animate_healing_effects
                    .after(move_agents)
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                autosave_game
                    .after(move_agents)
                    .after(apply_agent_commands)
                    .after(apply_building_commands)
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    instantiate_building_materials.after(apply_material_overrides),
                    sync_building_material_instances
                        .after(instantiate_building_materials)
                        .in_set(AgentSimulationSet),
                )
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                Update,
                (
                    process_injected_commands.after(inject_environment_commands),
                    start_queued_town_event.after(process_injected_commands),
                    apply_agent_commands.after(process_injected_commands),
                    animate_ping_pointers
                        .after(move_agents)
                        .after(apply_agent_commands),
                    apply_building_commands.after(process_injected_commands),
                    expire_inactive_building_placements.after(process_injected_commands),
                    sync_building_placers.after(expire_inactive_building_placements),
                    apply_building_placement_ghosts.after(sync_building_placers),
                    decay_traversal_wear.after(move_agents),
                    sync_traversal_wear_texture.after(decay_traversal_wear),
                    sync_path_surface_texture
                        .after(apply_building_commands)
                        .before(move_agents),
                    sync_building_placement_overlays
                        .after(process_injected_commands)
                        .after(apply_building_placement_ghosts),
                    sync_foliage_clearance
                        .after(apply_building_commands)
                        .after(decay_traversal_wear)
                        .after(sync_path_surface_texture)
                        .after(ground_loaded_surface_visuals),
                    sync_world_diagnostic_view
                        .after(process_injected_commands)
                        .after(sync_fine_navigation)
                        .after(sync_resource_nodes)
                        .after(sync_building_presentation),
                )
                    .in_set(GameplaySimulationSet)
                    .run_if(in_state(GameState::InGame)),
            )
            .add_systems(
                OnExit(GameState::InGame),
                (
                    tidal_music::stop_tidal_music,
                    save_on_gameplay_exit,
                    cleanup_world,
                    cleanup_menu_overlay,
                )
                    .chain(),
            )
            .add_systems(
                Update,
                (
                    sync_primary_window_settings,
                    apply_player_settings.run_if(resource_changed::<RuntimePlayerSettings>),
                ),
            )
            .add_systems(Update, ground_loaded_surface_visuals)
            .add_systems(
                Update,
                sync_authored_post_processing
                    .after(apply_player_settings)
                    .after(update_environment_presentation),
            )
            .add_systems(
                OnEnter(GameState::Credits),
                (cleanup_loading_screen, spawn_credits).chain(),
            )
            .add_systems(
                Update,
                (
                    drive_credits_animation,
                    update_credits_fireworks,
                    credits_skip_button.in_set(AccessibilityActionDispatch),
                    credits_input,
                )
                    .chain()
                    .run_if(in_state(GameState::Credits)),
            )
            .add_systems(
                OnExit(GameState::Credits),
                (cleanup_state_entities, cleanup_credits),
            );
    }
}
